# syntax=docker/dockerfile:1

FROM node:22-bookworm AS web
WORKDIR /src

COPY package.json package-lock.json tsconfig.json ./
COPY docs/package.json docs/package.json
COPY web-admin/package.json web-admin/package.json
COPY web-common/package.json web-common/package.json
COPY web-integration/package.json web-integration/package.json
COPY web-local/package.json web-local/package.json
RUN npm ci

COPY web-admin web-admin
COPY web-common web-common
COPY web-local web-local
COPY scripts scripts
RUN npm run build

FROM golang:1.26.5-bookworm AS binary
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY --from=web /src/web-local/build cli/pkg/web/embed/dist
RUN go build -trimpath -o /out/rill cli/main.go

FROM rilldata/rill:latest
USER root
COPY --from=binary /out/rill /usr/local/bin/rill
RUN chmod 755 /usr/local/bin/rill
USER rill
